# Site settings
title: Michael Roepke
email: roepke414@gmail.com
url: https://roepke414.github.io/
description: "My personal portfolio"
skills: "Engineer ready to better himself and the world"
meta_author: Roepke Michael

# Description
about1: "Automotive and motorcycle enthusiast with a passion for creating, engineering, and perfecting machined parts for the high performance world."
about2: "I am a motivated creator, with the want to design and build everything from simple projects to complex robotics."

# Color Settings (hex-codes without the leading hash-tag)
# I recommend using a site like this: https://www.canva.com/color-palette/
# It will help choose a starting pallete. But you'll need to do some tweaking.

#primary
#Background behind profile pic, and about section
#Choose this color somewhat conservatively. I recommend a darker color. Default: 1F2F42
  
#secondary
#Header, Footer, and large text labels
#This is your accent color, this can pop a little bit. Default: 1F67B4
  
#secondary-dark
#Section marker and copyright tag
#This color should be conservative, but compliment the accent color. Default: 233140
  
#background
#Background behind portfolio and contact forms. Default: 111111
  
color:
  primary: 628AB4
  secondary: 222222 #D6D3CA
  secondary-dark: 0D161E
  background: 111111
  text: ffffff

# Footer settings
footer:
  copyright: Michael Roepke
  location: Mankato, Minnesota
  social: Across the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: http://www.instagram.com/roepke414 
  - title: github
    url: http://github.com/roepke414
  - title: linkedin
    url: http://www.linkedin.com/in/michaelroepke


# Relative Path Links
profile_picture: img/profile.png
#baseurl: /instafolio

credits: "Instafolio is developed by Nick Nothom, and utilizes Github Pages, Jekyll, and the Freelancer theme."

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Build settings
markdown: kramdown
permalink: pretty
